version: "1"
services:
    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
    backend:
        build:
            context: ./backend
        ports:
            - "5000:5000"
        env_file:
            - ./backend/.flaskenv
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=govtech-employee

volumes:
  postgres_data: